// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jmpmucdoqkcpetdfnxrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcG11Y2RvcWtjcGV0ZGZueHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjAxNTcsImV4cCI6MjA3NTQ5NjE1N30.9DkLxkZNXz7G1zxK_ZiYWhpDzUIyI6wBcTfjCDA41Gg";

// Get the appropriate Supabase URL based on environment
const getSupabaseUrl = () => {
  // Check if we should use proxy (for security compliance)
  const useProxy = import.meta.env.VITE_USE_SUPABASE_PROXY === 'true';
  
  if (useProxy) {
    // Use the current domain with /api/supabase prefix
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    return origin + '/api/supabase';
  }
  
  // Default to direct Supabase URL
  return SUPABASE_URL;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(getSupabaseUrl(), SUPABASE_PUBLISHABLE_KEY);