// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseWithProxy, directSupabase } from './proxyClient';

const SUPABASE_URL = "https://gwfrchlimaugqnosvmbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3ZnJjaGxpbWF1Z3Fub3N2bWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTI1MTQsImV4cCI6MjA2MDM4ODUxNH0.iuCiOJeQdEr_2s-Ighup4vpYrRgoSEcNSopbBri3wYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use proxy-enabled client that automatically detects corporate firewalls
export const supabase = supabaseWithProxy;

// Export direct client for fallback if needed
export const supabaseDirect = directSupabase;

// Legacy export for backward compatibility
export const supabaseOriginal = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);